### ISSUE TITLE
test: 회원가입/로그인 test코드 작성

### ISSUE THREAD

**Issue by Yangdaehan** [geumgiri/geumgiri-server#13]
## 📌  Feature Issue

회원가입/ 로그인 test코드 작성

## 📝  To-do

- [x] 회원가입 test
- [x] 회원가입(아이디 중복) test
- [x] 로그인 test
- [x] 로그인 (없는 계정 정보) test
- [x] accessToken 재발급 받기 test
- [x] accessToken 재발급 받기(잘못된 refreshToken)일 때 test
