### ISSUE TITLE
[feat] 로그인 기능 구현

### ISSUE THREAD

**Issue by Yangdaehan** [geumgiri/geumgiri-server#2]
## 📌  Feature Issue

로그인 기능 구현 

## 📝  To-do

- [x] 스프링 시큐리티에 대해 공부 
- [x] 로그인/로그아웃 구현
- [x] 중복된 이메일 확인
- [x] DB 연결
