### ISSUE TITLE
feat: 대출 API 개발

### ISSUE THREAD

**Issue by Yangdaehan** [geumgiri/geumgiri-server#21]
## 📌  Feature Issue

대출 시스템을 구현합니다.

## 📝  To-do

1. **신용등급 관련 기능 추가**
- [ ] 대출 신청 시 신용등급을 낮추는 로직 구현
- [ ] 대출 상환 완료 시 신용등급을 회복시키는 로직 구현

2. **예외 처리 및 에러 메시지 관리**
- [ ] 기존 예외 메시지를 `ErrorStatus` enum에 통합하여 관리
- [ ] 필요한 경우 사용자에게 적절한 에러 메시지를 반환하는 로직 추가
