### ISSUE TITLE
feat: 결제 API 개발

### ISSUE THREAD

**Issue by 2522001** [geumgiri/geumgiri-server#25]
## 📌  Feature Issue

가상의 카드로 결제하는 기능을 개발합니다.
각 카드별 혜택을 반영하는 로직을 전략 패턴으로 구현합니다.

## 📝  To-do

- [ ] 결제 엔티티 생성
- [ ] 결제 목록 조회 API
- [ ] 결제 상세 조회 API
- [ ] 결제 승인 API
- [ ] 결제 취소 API
